#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#    Oct 30, 2018 08:32:38 PM EDT  platform: Linux

import sys
import mysql.connector
from tkinter import messagebox

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True


import admin_doctor_window_support


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1(root)
    admin_doctor_window_support.init(root, top)
    root.mainloop()


w = None


def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel(root)
    top = Toplevel1(w)
    admin_doctor_window_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_Toplevel1():
    global w
    w.destroy()
    w = None


class Toplevel1:

    def show_contact_info(self):
        try:
            patient_ssn = self.emergency_contact_info_patientID_textbox.get('1.0', 'end-1c')
            self.my_cursor.callproc('showcontact', (patient_ssn,))
            i = 0

            self.emergency_contact_info_listbox.delete(0, self.emergency_contact_info_listbox.size())
            for result in self.my_cursor.stored_results():
                list_contact_info = result.fetchall()
            for row in list_contact_info:
                self.emergency_contact_info_listbox.insert(i, row)
                i += 1



        except Exception:
            messagebox.showerror('Error', "Error displaying patient's emergency contact info")

    def show_diagnosis(self):
        try:
            patient_ssn = self.patient_diagnosis_patientID_textbox.get('1.0', 'end-1c')
            self.my_cursor.callproc('showdiagnosis', (patient_ssn,))
            i = 0

            self.patient_diagnosis_listbox.delete(0, self.patient_diagnosis_listbox.size())
            for result in self.my_cursor.stored_results():
                list_diagnosis_info = result.fetchall()
            for row in list_diagnosis_info:
                self.patient_diagnosis_listbox.insert(i, row)
                i += 1
        except Exception:
            messagebox.showerror('Error', "Error displaying patient's diagnosis")

    def update_diagnosis(self):
        patient_ssn = self.patient_diagnosis_patientID_textbox.get('1.0', 'end-1c')
        diagnosis_name = self.patient_diagnosis_diagnosis_name_textbox.get('1.0', 'end-1c')
        diagnosis_Id = self.patient_diagnosis_diagnosisID_textbox.get('1.0', 'end-1c')
        diagnosis_date = self.patient_diagnosis_diagnosis_date_textbox.get('1.0', 'end-1c')
        args = (patient_ssn, diagnosis_Id, diagnosis_date, diagnosis_name)

        try:
            self.my_cursor.callproc('updatediagnosis',args)
            self.my_db.commit()
            messagebox.showinfo('Update Diagnosis Success', "You successfully updated a patient's diagnosis")
        except Exception:
            messagebox.showerror('Error', "Error updating patient's diagnosis")

    def submit_diagnosis(self):
        patient_ssn = self.patient_diagnosis_patientID_textbox.get('1.0', 'end-1c')
        diagnosis_name = self.patient_diagnosis_diagnosis_name_textbox.get('1.0', 'end-1c')
        diagnosis_id = self.patient_diagnosis_diagnosisID_textbox.get('1.0', 'end-1c')
        diagnosis_date = self.patient_diagnosis_diagnosis_date_textbox.get('1.0', 'end-1c')
        args = (patient_ssn, diagnosis_id, diagnosis_name, diagnosis_date)

        try:
            self.my_cursor.callproc('insertdiagnosis', args)
            self.my_db.commit()

            messagebox.showinfo('Submit Diagnosis Success', "You successfully submitted a patient's new diagnosis")
        except Exception:
            messagebox.showerror('Error', "Error submitting patient's diagnosis")

    def show_drug_treatment(self):
        try:
            patient_ssn = self.patient_drug_treament_patientssn_textbox.get('1.0', 'end-1c')
            self.my_cursor.callproc('showdrugtreatment', (patient_ssn,))
            i = 0

            self.patient_drug_treatment_listbox.delete(0, self.patient_drug_treatment_listbox.size())
            for result in self.my_cursor.stored_results():
                list_drug_info = result.fetchall()
            for row in list_drug_info:
                self.patient_drug_treatment_listbox.insert(i, row)
                i += 1
        except Exception:
            messagebox.showerror('Error', "Error displaying patient's drug treatment")

    def update_drug_treatment(self):
        patient_ssn = self.patient_drug_treament_patientssn_textbox.get('1.0', 'end-1c')
        drug_Id = self.patient_drug_treatment_drugID_textbox.get('1.0', 'end-1c')
        drug_Name = self.patient_drug_treatment_drug_name_textbox.get('1.0', 'end-1c')
        drug_Date = self.patient_drug_treatment_drugdate_textbox.get('1.0', 'end-1c')
        args = (patient_ssn, drug_Id, drug_Name, drug_Date)

        try:

            self.my_cursor.callproc('updatedrugtreatment', args)
            self.my_db.commit()
            messagebox.showinfo('Update Drug Treatment Success', "You successfully updated a patient's drug treatment")
        except Exception:
            messagebox.showerror('Error', "Error updating patient's diagnosis")

    def submit_drug_treatment(self):
        patient_ssn = self.patient_drug_treament_patientssn_textbox.get('1.0', 'end-1c')

        drug_Id = self.patient_drug_treatment_drugID_textbox.get('1.0', 'end-1c')
        drug_Name = self.patient_drug_treatment_drug_name_textbox.get('1.0', 'end-1c')
        drug_Date = self.patient_drug_treatment_drugdate_textbox.get('1.0', 'end-1c')
        args = (patient_ssn, drug_Id, drug_Name, drug_Date)

        try:
            self.my_cursor.callproc('insertdrugtreatment', args)
            self.my_db.commit()
            messagebox.showinfo('Submit Diagnosis Success', "You successfully submitted a patient's new drug treatment")
        except Exception:
            messagebox.showerror('Error', "Error submitting patient's drug treatment")




    def show_patient_info(self):
        try:

            self.my_cursor.execute("SELECT * FROM patient;")
            list_patients = self.my_cursor.fetchall()
            i = 0
            self.Listbox3.delete(0, self.Listbox3.size())
            for row in list_patients:
                self.Listbox3.insert(i, row)
                i = i + 1
        except Exception:
            messagebox.showerror('Error', 'Error displaying patient info')

    def update_patient_info(self):
        patient_ssn = self.patient_information_patientssn_textbox.get('1.0', 'end-1c')
        patient_name = self.patient_info_fullname_textbox.get('1.0', 'end-1c')
        patient_gender = self.patient_info_gender_textbox.get('1.0', 'end-1c')
        patient_dob = self.patient_info_DOB_textbox.get('1.0', 'end-1c')
        patient_address = self.patient_info_address_textbox.get('1.0', 'end-1c')
        patient_phone = self.Text5.get('1.0', 'end-1c')
        patient_enumber = self.patient_info_emergency_contact_phone_textbox.get('1.0', 'end-1c')
        patient_ename = self.patient_emergencycontact_name_textbox.get('1.0', 'end-1c')
        args = (patient_ssn, patient_name, patient_gender, patient_dob, patient_address, patient_phone, patient_enumber, patient_ename )

        try:
            self.my_cursor.callproc('updatepatientinfo', args)
            self.my_db.commit()

            messagebox.showinfo('Success', "You successfully updated patient info")
        except Exception:
            messagebox.showerror('Error changing',
                                 'Please make sure you have re-entered all of the patient. Also you cannot modify SSN!')

    def insert_patient_records(self):
        patient_ssn = self.patient_records_patientID_textbox.get('1.0', 'end-1c')
        patient_admission = self.patient_records_admission_date_textbox.get('1.0', 'end-1c')
        patient_release = self.patient_records_discharge_date_textbox.get('1.0', 'end-1c')
        patient_fees = self.patient_records_fee_textbox.get('1.0', 'end-1c')

        insert_patient_record_command = "INSERT INTO patientrecord (SSN, admissionDate, releaseDate, fees)" \
                                        " VALUES (%s,%s,%s,%s)"
        patient_record_details = (patient_ssn, patient_admission, patient_release, patient_fees)
        try:
            self.my_cursor.execute(insert_patient_record_command, patient_record_details)
            self.my_db.commit()
            messagebox.showinfo('Success', "You successfully inserted patient records")
        except Exception:
            messagebox.showerror('Error', 'Please make sure you\'ve entered all fields and a valid SSN')

    def show_patient_records(self):
        patient_ssn = self.patient_records_patientID_textbox.get('1.0', 'end-1c')
        show_patient_record_command = f"SELECT pr.SSN, patientName, admissionDate," \
                                      f"releaseDate, fees FROM patient p JOIN" \
                                      f" patientrecord pr ON pr.SSN = p.SSN AND " \
                                      f"pr.SSN = '{patient_ssn}'"
        try:
            self.my_cursor.execute(show_patient_record_command)
            list_patient_records = self.my_cursor.fetchall()
            i = 0
            self.patient_records_listbox.delete(0, self.patient_records_listbox.size())
            for row in list_patient_records:
                self.patient_records_listbox.insert(i, row)
                i = i + 1
        except Exception:
            messagebox.showerror('Error!', 'There was an error in showing patient records')

    def update_patient_records(self):
        patient_ssn = self.patient_records_patientID_textbox.get('1.0', 'end-1c')
        patient_admission = self.patient_records_admission_date_textbox.get('1.0', 'end-1c')
        patient_release = self.patient_records_discharge_date_textbox.get('1.0', 'end-1c')
        patient_fees = self.patient_records_fee_textbox.get('1.0', 'end-1c')

        update_command = f"UPDATE patientrecord SET" \
                         f" admissionDate = '{patient_admission}', " \
                         f"releaseDate = '{patient_release}'," \
                         f" fees = '{patient_fees}' WHERE SSN = '{patient_ssn}' AND admissionDate = '{patient_admission}'"
        try:
            self.my_cursor.execute(update_command)
            self.my_db.commit()
            messagebox.showinfo('Success', "You successfully updated patient records")
        except Exception:
            messagebox.showerror('Error!',
                                 'There was an error in updating patient records: Enter all fields and an existing SSN')

    def insert_patient_surgery(self):
        patient_ssn = self.patient_surgeries_patient_ssn_textbox.get('1.0', 'end-1c')
        surgery_id = self.patient_surgeries_surgeryID_textbox.get('1.0', 'end-1c')
        surgery_name = self.patient_surgeries_surgery_name_textbox.get('1.0', 'end-1c')
        begin_date = self.patient_surgeries_start_date_textbox.get('1.0', 'end-1c')
        end_date = self.patient_surgeries_end_date_textbox.get('1.0', 'end-1c')
        results = self.patient_surgeries_result_textbox.get('1.0', 'end-1c')
        surgery_details = (patient_ssn, surgery_id, surgery_name, begin_date, end_date, results)

        try:

            self.my_cursor.callproc('insertsurgery', surgery_details)
            self.my_db.commit()
            messagebox.showinfo('Success', "You successfully inserted patient surgery")
        except Exception:
            messagebox.showerror('Error', 'There was an error in entering patient surgery!')

    def show_surgery(self):
        patient_ssn = self.patient_surgeries_patient_ssn_textbox.get('1.0', 'end-1c')
        # show_command = f"SELECT s.SSN, patientName, surgeryID, surgeryName, beginDate," \
        #                f" endDate, results FROM patient p JOIN patientsurgery s ON " \
        #                f"p.SSN = '{patient_ssn}' AND s.SSN = '{patient_ssn}'"
        try:
            self.my_cursor.callproc('showsurgeries', (patient_ssn,))
            i = 0

            self.Listbox2.delete(0, self.Listbox2.size())
            for result in self.my_cursor.stored_results():
                list_surgery_info = result.fetchall()
            for row in list_surgery_info:
                self.Listbox2.insert(i, row)
                i += 1
        except Exception:
            messagebox.showerror('Error', 'There was an error in showing surgery info!')

    def update_surgery(self):
        patient_ssn = self.patient_surgeries_patient_ssn_textbox.get('1.0', 'end-1c')
        surgery_id = self.patient_surgeries_surgeryID_textbox.get('1.0', 'end-1c')
        surgery_name = self.patient_surgeries_surgery_name_textbox.get('1.0', 'end-1c')
        begin_date = self.patient_surgeries_start_date_textbox.get('1.0', 'end-1c')
        end_date = self.patient_surgeries_end_date_textbox.get('1.0', 'end-1c')
        results = self.patient_surgeries_result_textbox.get('1.0', 'end-1c')
        surgery_details = (patient_ssn, surgery_id, surgery_name, begin_date, end_date, results)
        # update_command = f"UPDATE patientsurgery SET " \
        #                  f"surgeryID = '{surgery_id}', " \
        #                  f"surgeryName = '{surgery_name}', " \
        #                  f"beginDate = '{begin_date}', " \
        #                  f"endDate = '{end_date}', " \
        #                  f"results = '{results}' WHERE SSN = '{patient_ssn}' AND beginDate = '{begin_date}'"
        try:
            self.my_cursor.callproc('updatesurgeries', surgery_details)
            self.my_db.commit()
            messagebox.showinfo('Success', "You successfully updated surgery info")
        except Exception:
            messagebox.showerror('Error', 'There was an error in updating surgery!')

    def __init__(self, top=None):
        try:
            self.my_db = mysql.connector.connect(
                host="localhost",
                user="root", #root
                password="csc336", #csc336
                database="hospital")

            self.my_cursor = self.my_db.cursor()

        except Exception:
            messagebox.showerror('Error', 'Error while connecting to mysql database')

        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#d9d9d9'  # X11 color: 'gray85'
        font9 = "-family {DejaVu Sans} -size 7 -weight normal -slant " \
                "italic -underline 0 -overstrike 0"

        top.geometry("1373x729+67+27")
        top.title("New Toplevel")
        top.configure(background="#d6d6d6")
        top.configure(highlightcolor="black")

        self.emergency_contact_labelframe = tk.LabelFrame(top)
        self.emergency_contact_labelframe.place(relx=0.503, rely=0.027
                                                , relheight=0.254, relwidth=0.466)
        self.emergency_contact_labelframe.configure(relief='groove')
        self.emergency_contact_labelframe.configure(text='''Emergency Contact Information''')
        self.emergency_contact_labelframe.configure(background="#d8d8d8")
        self.emergency_contact_labelframe.configure(width=640)

        self.emergency_contact_info_patient_ssn_label = tk.Label(self.emergency_contact_labelframe)
        self.emergency_contact_info_patient_ssn_label.place(relx=0.063
                                                            , rely=0.162, height=21, width=80, bordermode='ignore')
        self.emergency_contact_info_patient_ssn_label.configure(activebackground="#f9f9f9")
        self.emergency_contact_info_patient_ssn_label.configure(text='''Patient SSN''')

        self.emergency_contact_info_patientID_textbox = tk.Text(self.emergency_contact_labelframe)
        self.emergency_contact_info_patientID_textbox.place(relx=0.203
                                                            , rely=0.162, relheight=0.13, relwidth=0.166
                                                            , bordermode='ignore')
        self.emergency_contact_info_patientID_textbox.configure(background="white")
        self.emergency_contact_info_patientID_textbox.configure(font="TkTextFont")
        self.emergency_contact_info_patientID_textbox.configure(selectbackground="#c4c4c4")
        self.emergency_contact_info_patientID_textbox.configure(width=106)
        self.emergency_contact_info_patientID_textbox.configure(wrap='word')

        self.show_emergency_contact_info_button = tk.Button(self.emergency_contact_labelframe)
        self.show_emergency_contact_info_button.place(relx=0.484, rely=0.135
                                                      , height=31, width=181, bordermode='ignore')
        self.show_emergency_contact_info_button.configure(activebackground="#d9d9d9")
        self.show_emergency_contact_info_button.configure(text='''Show Contact Information''')
        self.show_emergency_contact_info_button.configure(command=self.show_contact_info)

        self.emergency_contact_info_listbox = tk.Listbox(self.emergency_contact_labelframe)
        self.emergency_contact_info_listbox.place(relx=0.016, rely=0.432
                                                  , relheight=0.465, relwidth=0.959, bordermode='ignore')
        self.emergency_contact_info_listbox.configure(background="white")
        self.emergency_contact_info_listbox.configure(font="TkFixedFont")
        self.emergency_contact_info_listbox.configure(selectbackground="#c4c4c4")
        self.emergency_contact_info_listbox.configure(width=614)

        self.patient_diagnosis_labelframe = tk.LabelFrame(top)
        self.patient_diagnosis_labelframe.place(relx=0.503, rely=0.288
                                                , relheight=0.336, relwidth=0.466)
        self.patient_diagnosis_labelframe.configure(relief='groove')
        self.patient_diagnosis_labelframe.configure(text='''Patient Diagnosis''')
        self.patient_diagnosis_labelframe.configure(width=640)

        self.patient_diagnosis_patientssn_label = tk.Label(self.patient_diagnosis_labelframe)
        self.patient_diagnosis_patientssn_label.place(relx=0.063, rely=0.122
                                                      , height=21, width=88, bordermode='ignore')
        self.patient_diagnosis_patientssn_label.configure(activebackground="#f9f9f9")
        self.patient_diagnosis_patientssn_label.configure(text='''Patient SSN''')

        self.patient_diagnosis_patientID_textbox = tk.Text(self.patient_diagnosis_labelframe)
        self.patient_diagnosis_patientID_textbox.place(relx=0.203, rely=0.122
                                                       , relheight=0.098, relwidth=0.166, bordermode='ignore')
        self.patient_diagnosis_patientID_textbox.configure(background="white")
        self.patient_diagnosis_patientID_textbox.configure(font="TkTextFont")
        self.patient_diagnosis_patientID_textbox.configure(selectbackground="#c4c4c4")
        self.patient_diagnosis_patientID_textbox.configure(width=106)
        self.patient_diagnosis_patientID_textbox.configure(wrap='word')

        self.patient_diagnosis_diagnosis_name_label = tk.Label(self.patient_diagnosis_labelframe)
        self.patient_diagnosis_diagnosis_name_label.place(relx=0.063, rely=0.286
                                                          , height=21, width=111, bordermode='ignore')
        self.patient_diagnosis_diagnosis_name_label.configure(activebackground="#f9f9f9")
        self.patient_diagnosis_diagnosis_name_label.configure(text='''Diagnosis Name''')

        self.patient_diagnosis_diagnosisID_label = tk.Label(self.patient_diagnosis_labelframe)
        self.patient_diagnosis_diagnosisID_label.place(relx=0.380, rely=0.122
                                                       , height=21, width=86, bordermode='ignore')
        self.patient_diagnosis_diagnosisID_label.configure(activebackground="#f9f9f9")
        self.patient_diagnosis_diagnosisID_label.configure(text='''Diagnosis ID''')

        self.patient_diagnosis_diagnosis_date = tk.Label(self.patient_diagnosis_labelframe)
        self.patient_diagnosis_diagnosis_date.place(relx=0.516, rely=0.286
                                                    , height=21, width=103, bordermode='ignore')
        self.patient_diagnosis_diagnosis_date.configure(activebackground="#f9f9f9")
        self.patient_diagnosis_diagnosis_date.configure(text='''Diagnosis Date''')

        self.patient_diagnosis_diagnosis_name_textbox = tk.Text(self.patient_diagnosis_labelframe)
        self.patient_diagnosis_diagnosis_name_textbox.place(relx=0.25, rely=0.286
                                                            , relheight=0.098, relwidth=0.15, bordermode='ignore')
        self.patient_diagnosis_diagnosis_name_textbox.configure(background="white")
        self.patient_diagnosis_diagnosis_name_textbox.configure(font="TkTextFont")
        self.patient_diagnosis_diagnosis_name_textbox.configure(selectbackground="#c4c4c4")
        self.patient_diagnosis_diagnosis_name_textbox.configure(width=96)
        self.patient_diagnosis_diagnosis_name_textbox.configure(wrap='word')

        self.patient_diagnosis_diagnosisID_textbox = tk.Text(self.patient_diagnosis_labelframe)
        self.patient_diagnosis_diagnosisID_textbox.place(relx=0.502, rely=0.122
                                                         , relheight=0.098, relwidth=0.119, bordermode='ignore')
        self.patient_diagnosis_diagnosisID_textbox.configure(background="white")
        self.patient_diagnosis_diagnosisID_textbox.configure(font="TkTextFont")
        self.patient_diagnosis_diagnosisID_textbox.configure(selectbackground="#c4c4c4")
        self.patient_diagnosis_diagnosisID_textbox.configure(width=76)
        self.patient_diagnosis_diagnosisID_textbox.configure(wrap='word')

        self.patient_diagnosis_diagnosis_date_textbox = tk.Text(self.patient_diagnosis_labelframe)
        self.patient_diagnosis_diagnosis_date_textbox.place(relx=0.688
                                                            , rely=0.286, relheight=0.098, relwidth=0.134
                                                            , bordermode='ignore')
        self.patient_diagnosis_diagnosis_date_textbox.configure(background="white")
        self.patient_diagnosis_diagnosis_date_textbox.configure(font="TkTextFont")
        self.patient_diagnosis_diagnosis_date_textbox.configure(selectbackground="#c4c4c4")
        self.patient_diagnosis_diagnosis_date_textbox.configure(width=86)
        self.patient_diagnosis_diagnosis_date_textbox.configure(wrap='word')

        self.patient_diagnosis_submit_button = tk.Button(self.patient_diagnosis_labelframe)
        self.patient_diagnosis_submit_button.place(relx=0.641, rely=0.408
                                                   , height=31, width=104, bordermode='ignore')
        self.patient_diagnosis_submit_button.configure(activebackground="#d9d9d9")
        self.patient_diagnosis_submit_button.configure(text='''Submit''')
        self.patient_diagnosis_submit_button.configure(command=self.submit_diagnosis)

        self.patient_diagnosis_update_button = tk.Button(self.patient_diagnosis_labelframe)
        self.patient_diagnosis_update_button.place(relx=0.438, rely=0.408
                                                   , height=31, width=106, bordermode='ignore')
        self.patient_diagnosis_update_button.configure(activebackground="#d9d9d9")
        self.patient_diagnosis_update_button.configure(text='''Update''')
        self.patient_diagnosis_update_button.configure(command=self.update_diagnosis)

        self.patient_diagnosis_show_diagnosis_button = tk.Button(self.patient_diagnosis_labelframe)
        self.patient_diagnosis_show_diagnosis_button.place(relx=0.195, rely=0.408
                                                           , height=31, width=125, bordermode='ignore')
        self.patient_diagnosis_show_diagnosis_button.configure(activebackground="#d9d9d9")
        self.patient_diagnosis_show_diagnosis_button.configure(text='''Show Diagnosis''')
        self.patient_diagnosis_show_diagnosis_button.configure(command=self.show_diagnosis)

        self.patient_diagnosis_listbox = tk.Listbox(self.patient_diagnosis_labelframe)
        self.patient_diagnosis_listbox.place(relx=0.016, rely=0.571
                                             , relheight=0.351, relwidth=0.959, bordermode='ignore')
        self.patient_diagnosis_listbox.configure(background="white")
        self.patient_diagnosis_listbox.configure(font="TkFixedFont")
        self.patient_diagnosis_listbox.configure(selectbackground="#c4c4c4")
        self.patient_diagnosis_listbox.configure(width=614)

        self.patient_diagnosis_yyyymmdd_label = tk.Label(self.patient_diagnosis_labelframe)
        self.patient_diagnosis_yyyymmdd_label.place(relx=0.703, rely=0.245
                                                    , height=11, width=56, bordermode='ignore')
        self.patient_diagnosis_yyyymmdd_label.configure(activebackground="#f9f9f9")
        self.patient_diagnosis_yyyymmdd_label.configure(font=font9)
        self.patient_diagnosis_yyyymmdd_label.configure(text='''YYYYMMDD''')

        self.patient_records_labelframe = tk.LabelFrame(top)
        self.patient_records_labelframe.place(relx=0.015, rely=0.288
                                              , relheight=0.336, relwidth=0.466)
        self.patient_records_labelframe.configure(relief='groove')
        self.patient_records_labelframe.configure(text='''Patient Records''')
        self.patient_records_labelframe.configure(width=640)

        self.patient_records_patientssn_label = tk.Label(self.patient_records_labelframe)
        self.patient_records_patientssn_label.place(relx=0.063, rely=0.122
                                                    , height=21, width=80, bordermode='ignore')
        self.patient_records_patientssn_label.configure(activebackground="#f9f9f9")
        self.patient_records_patientssn_label.configure(text='''Patient SSN''')

        self.patient_records_patientID_textbox = tk.Text(self.patient_records_labelframe)
        self.patient_records_patientID_textbox.place(relx=0.203, rely=0.122
                                                     , relheight=0.098, relwidth=0.166, bordermode='ignore')
        self.patient_records_patientID_textbox.configure(background="white")
        self.patient_records_patientID_textbox.configure(font="TkTextFont")
        self.patient_records_patientID_textbox.configure(selectbackground="#c4c4c4")
        self.patient_records_patientID_textbox.configure(width=106)
        self.patient_records_patientID_textbox.configure(wrap='word')

        self.patient_records_admission_date_label = tk.Label(self.patient_records_labelframe)
        self.patient_records_admission_date_label.place(relx=0.063, rely=0.286
                                                        , height=21, width=107, bordermode='ignore')
        self.patient_records_admission_date_label.configure(activebackground="#f9f9f9")
        self.patient_records_admission_date_label.configure(text='''Admission Date''')

        self.patient_records_admission_date_textbox = tk.Text(self.patient_records_labelframe)
        self.patient_records_admission_date_textbox.place(relx=0.25, rely=0.286
                                                          , relheight=0.098, relwidth=0.134, bordermode='ignore')
        self.patient_records_admission_date_textbox.configure(background="white")
        self.patient_records_admission_date_textbox.configure(font="TkTextFont")
        self.patient_records_admission_date_textbox.configure(selectbackground="#c4c4c4")
        self.patient_records_admission_date_textbox.configure(width=86)
        self.patient_records_admission_date_textbox.configure(wrap='word')

        self.patient_records_discharge_date_label = tk.Label(self.patient_records_labelframe)
        self.patient_records_discharge_date_label.place(relx=0.453, rely=0.286
                                                        , height=21, width=104, bordermode='ignore')
        self.patient_records_discharge_date_label.configure(activebackground="#f9f9f9")
        self.patient_records_discharge_date_label.configure(text='''Discharge Date''')

        self.patient_records_yyyymmdd_label1 = tk.Label(self.patient_records_labelframe)
        self.patient_records_yyyymmdd_label1.place(relx=0.266, rely=0.245
                                                   , height=11, width=61, bordermode='ignore')
        self.patient_records_yyyymmdd_label1.configure(activebackground="#f9f9f9")
        self.patient_records_yyyymmdd_label1.configure(font=font9)
        self.patient_records_yyyymmdd_label1.configure(text='''YYYYMMDD''')

        self.patient_records_discharge_date_textbox = tk.Text(self.patient_records_labelframe)
        self.patient_records_discharge_date_textbox.place(relx=0.641, rely=0.286
                                                          , relheight=0.098, relwidth=0.134, bordermode='ignore')
        self.patient_records_discharge_date_textbox.configure(background="white")
        self.patient_records_discharge_date_textbox.configure(font="TkTextFont")
        self.patient_records_discharge_date_textbox.configure(selectbackground="#c4c4c4")
        self.patient_records_discharge_date_textbox.configure(width=86)
        self.patient_records_discharge_date_textbox.configure(wrap='word')

        self.patient_records_yyyymmdd_label2 = tk.Label(self.patient_records_labelframe)
        self.patient_records_yyyymmdd_label2.place(relx=0.656, rely=0.245
                                                   , height=11, width=56, bordermode='ignore')
        self.patient_records_yyyymmdd_label2.configure(activebackground="#f9f9f9")
        self.patient_records_yyyymmdd_label2.configure(font=font9)
        self.patient_records_yyyymmdd_label2.configure(text='''YYYYMMDD''')

        self.patient_records_fee_label = tk.Label(self.patient_records_labelframe)
        self.patient_records_fee_label.place(relx=0.547, rely=0.122, height=21
                                             , width=28, bordermode='ignore')
        self.patient_records_fee_label.configure(activebackground="#f9f9f9")
        self.patient_records_fee_label.configure(text='''Fee''')

        self.patient_records_fee_textbox = tk.Text(self.patient_records_labelframe)
        self.patient_records_fee_textbox.place(relx=0.641, rely=0.122
                                               , relheight=0.098, relwidth=0.119, bordermode='ignore')
        self.patient_records_fee_textbox.configure(background="white")
        self.patient_records_fee_textbox.configure(font="TkTextFont")
        self.patient_records_fee_textbox.configure(selectbackground="#c4c4c4")
        self.patient_records_fee_textbox.configure(width=76)
        self.patient_records_fee_textbox.configure(wrap='word')

        self.patient_records_dollar_sign_label = tk.Label(self.patient_records_labelframe)
        self.patient_records_dollar_sign_label.place(relx=0.625, rely=0.122
                                                     , height=23, width=10, bordermode='ignore')
        self.patient_records_dollar_sign_label.configure(activebackground="#f9f9f9")
        self.patient_records_dollar_sign_label.configure(text='''$''')

        self.patient_records_submit_button = tk.Button(self.patient_records_labelframe)
        self.patient_records_submit_button.place(relx=0.656, rely=0.408
                                                 , height=30, width=118, bordermode='ignore')
        self.patient_records_submit_button.configure(activebackground="#d9d9d9")
        self.patient_records_submit_button.configure(text='''Submit''')
        self.patient_records_submit_button.configure(command=self.insert_patient_records)

        self.patient_records_update_button = tk.Button(self.patient_records_labelframe)
        self.patient_records_update_button.place(relx=0.422, rely=0.408
                                                 , height=31, width=118, bordermode='ignore')
        self.patient_records_update_button.configure(activebackground="#d9d9d9")
        self.patient_records_update_button.configure(text='''Update''')
        self.patient_records_update_button.configure(command=self.update_patient_records)

        self.patient_records_show_records_button = tk.Button(self.patient_records_labelframe)
        self.patient_records_show_records_button.place(relx=0.203, rely=0.408
                                                       , height=31, width=109, bordermode='ignore')
        self.patient_records_show_records_button.configure(activebackground="#d9d9d9")
        self.patient_records_show_records_button.configure(text='''Show Records''')
        self.patient_records_show_records_button.configure(command=self.show_patient_records)

        self.patient_records_listbox = tk.Listbox(self.patient_records_labelframe)
        self.patient_records_listbox.place(relx=0.016, rely=0.571
                                           , relheight=0.351, relwidth=0.959, bordermode='ignore')
        self.patient_records_listbox.configure(background="white")
        self.patient_records_listbox.configure(font="TkFixedFont")
        self.patient_records_listbox.configure(selectbackground="#c4c4c4")
        self.patient_records_listbox.configure(width=614)

        self.patient_drug_treatment_labelframe = tk.LabelFrame(top)
        self.patient_drug_treatment_labelframe.place(relx=0.503, rely=0.631
                                                     , relheight=0.336, relwidth=0.466)
        self.patient_drug_treatment_labelframe.configure(relief='groove')
        self.patient_drug_treatment_labelframe.configure(text='''Patient Drug Treatment''')
        self.patient_drug_treatment_labelframe.configure(width=640)

        self.patient_drug_treatment_patientID_label = tk.Label(self.patient_drug_treatment_labelframe)
        self.patient_drug_treatment_patientID_label.place(relx=0.078, rely=0.163
                                                          , height=21, width=4, bordermode='ignore')
        self.patient_drug_treatment_patientID_label.configure(activebackground="#f9f9f9")

        self.patient_drug_treatment_patientssn_label = tk.Label(self.patient_drug_treatment_labelframe)
        self.patient_drug_treatment_patientssn_label.place(relx=0.078, rely=0.122
                                                           , height=21, width=80, bordermode='ignore')
        self.patient_drug_treatment_patientssn_label.configure(activebackground="#f9f9f9")
        self.patient_drug_treatment_patientssn_label.configure(text='''Patient SSN''')

        self.patient_drug_treatment_drug_name_label = tk.Label(self.patient_drug_treatment_labelframe)
        self.patient_drug_treatment_drug_name_label.place(relx=0.5, rely=0.122
                                                          , height=21, width=78, bordermode='ignore')
        self.patient_drug_treatment_drug_name_label.configure(activebackground="#f9f9f9")
        self.patient_drug_treatment_drug_name_label.configure(text='''Drug Name''')

        self.patient_drug_treatment_drugID_label = tk.Label(self.patient_drug_treatment_labelframe)
        self.patient_drug_treatment_drugID_label.place(relx=0.4, rely=0.286
                                                       , height=21, width=63, bordermode='ignore')
        self.patient_drug_treatment_drugID_label.configure(activebackground="#f9f9f9")
        self.patient_drug_treatment_drugID_label.configure(text='''Drug ID''')
        # Drug date label
        self.patient_drug_treatment_drugdate_label = tk.Label(self.patient_drug_treatment_labelframe)
        self.patient_drug_treatment_drugdate_label.place(relx=0.65, rely=0.286
                                                       , height=21, width=100, bordermode='ignore')
        self.patient_drug_treatment_drugdate_label.configure(activebackground="#f9f9f9")
        self.patient_drug_treatment_drugdate_label.configure(text='''Date(YYYYMMDD)''')

        # self.patient_drug_treatment_reason_label = tk.Label(self.patient_drug_treatment_labelframe)
        # self.patient_drug_treatment_reason_label.place(relx=0.078
        #                                                     , rely=0.286, height=21, width=86, bordermode='ignore')
        # self.patient_drug_treatment_reason_label.configure(activebackground="#f9f9f9")
        # self.patient_drug_treatment_reason_label.configure(text='''Reason''')

        self.patient_drug_treatment_submit_button = tk.Button(self.patient_drug_treatment_labelframe)
        self.patient_drug_treatment_submit_button.place(relx=0.656, rely=0.408
                                                        , height=29, width=102, bordermode='ignore')
        self.patient_drug_treatment_submit_button.configure(activebackground="#d9d9d9")
        self.patient_drug_treatment_submit_button.configure(text='''Submit''')
        self.patient_drug_treatment_submit_button.configure(command=self.submit_drug_treatment)

        self.patient_drug_treatment_update_button = tk.Button(self.patient_drug_treatment_labelframe)
        self.patient_drug_treatment_update_button.place(relx=0.453, rely=0.408
                                                        , height=29, width=103, bordermode='ignore')
        self.patient_drug_treatment_update_button.configure(activebackground="#d9d9d9")
        self.patient_drug_treatment_update_button.configure(text='''Update''')
        self.patient_drug_treatment_update_button.configure(command=self.update_drug_treatment)

        self.patient_drug_treatment_show_drug_treatments_button = tk.Button(self.patient_drug_treatment_labelframe)
        self.patient_drug_treatment_show_drug_treatments_button.place(relx=0.141
                                                                      , rely=0.408, height=29, width=175,
                                                                      bordermode='ignore')
        self.patient_drug_treatment_show_drug_treatments_button.configure(activebackground="#d9d9d9")
        self.patient_drug_treatment_show_drug_treatments_button.configure(text='''Show Drug Treatments''')
        self.patient_drug_treatment_show_drug_treatments_button.configure(command=self.show_drug_treatment)

        self.patient_drug_treatment_listbox = tk.Listbox(self.patient_drug_treatment_labelframe)
        self.patient_drug_treatment_listbox.place(relx=0.016, rely=0.571
                                                  , relheight=0.351, relwidth=0.959, bordermode='ignore')
        self.patient_drug_treatment_listbox.configure(background="white")
        self.patient_drug_treatment_listbox.configure(font="TkFixedFont")
        self.patient_drug_treatment_listbox.configure(selectbackground="#c4c4c4")
        self.patient_drug_treatment_listbox.configure(width=614)

        self.patient_drug_treament_patientssn_textbox = tk.Text(self.patient_drug_treatment_labelframe)
        self.patient_drug_treament_patientssn_textbox.place(relx=0.219
                                                            , rely=0.122, relheight=0.098, relwidth=0.166
                                                            , bordermode='ignore')
        self.patient_drug_treament_patientssn_textbox.configure(background="white")
        self.patient_drug_treament_patientssn_textbox.configure(font="TkTextFont")
        self.patient_drug_treament_patientssn_textbox.configure(selectbackground="#c4c4c4")
        self.patient_drug_treament_patientssn_textbox.configure(width=106)
        self.patient_drug_treament_patientssn_textbox.configure(wrap='word')

        self.patient_drug_treatment_drug_name_textbox = tk.Text(self.patient_drug_treatment_labelframe)
        self.patient_drug_treatment_drug_name_textbox.place(relx=0.641
                                                            , rely=0.122, relheight=0.098, relwidth=0.291
                                                            , bordermode='ignore')
        self.patient_drug_treatment_drug_name_textbox.configure(background="white")
        self.patient_drug_treatment_drug_name_textbox.configure(font="TkTextFont")
        self.patient_drug_treatment_drug_name_textbox.configure(selectbackground="#c4c4c4")
        self.patient_drug_treatment_drug_name_textbox.configure(width=186)
        self.patient_drug_treatment_drug_name_textbox.configure(wrap='word')

        self.patient_drug_treatment_drugID_textbox = tk.Text(self.patient_drug_treatment_labelframe)
        self.patient_drug_treatment_drugID_textbox.place(relx=0.5, rely=0.286
                                                         , relheight=0.098, relwidth=0.134, bordermode='ignore')
        self.patient_drug_treatment_drugID_textbox.configure(background="white")
        self.patient_drug_treatment_drugID_textbox.configure(font="TkTextFont")
        self.patient_drug_treatment_drugID_textbox.configure(selectbackground="#c4c4c4")
        self.patient_drug_treatment_drugID_textbox.configure(width=86)
        self.patient_drug_treatment_drugID_textbox.configure(wrap='word')

        # Added date
        self.patient_drug_treatment_drugdate_textbox = tk.Text(self.patient_drug_treatment_labelframe)
        self.patient_drug_treatment_drugdate_textbox.place(relx=0.830, rely=0.286
                                                         , relheight=0.098, relwidth=0.134, bordermode='ignore')
        self.patient_drug_treatment_drugdate_textbox.configure(background="white")
        self.patient_drug_treatment_drugdate_textbox.configure(font="TkTextFont")
        self.patient_drug_treatment_drugdate_textbox.configure(selectbackground="#c4c4c4")
        self.patient_drug_treatment_drugdate_textbox.configure(width=86)
        self.patient_drug_treatment_drugdate_textbox.configure(wrap='word')

        # self.patient_drug_treatment_reason_textbox = tk.Text(self.patient_drug_treatment_labelframe)
        # self.patient_drug_treatment_reason_textbox.place(relx=0.234
        #                                                       , rely=0.286, relheight=0.098, relwidth=0.134
        #                                                       , bordermode='ignore')
        # self.patient_drug_treatment_reason_textbox.configure(background="white")
        # self.patient_drug_treatment_reason_textbox.configure(font="TkTextFont")
        # self.patient_drug_treatment_reason_textbox.configure(selectbackground="#c4c4c4")
        # self.patient_drug_treatment_reason_textbox.configure(width=86)
        # self.patient_drug_treatment_reason_textbox.configure(wrap='word')

        self.patient_surgeries_labelframe = tk.LabelFrame(top)
        self.patient_surgeries_labelframe.place(relx=0.015, rely=0.631
                                                , relheight=0.336, relwidth=0.466)
        self.patient_surgeries_labelframe.configure(relief='groove')
        self.patient_surgeries_labelframe.configure(text='''Patient Surgeries''')
        self.patient_surgeries_labelframe.configure(width=640)

        self.patient_surgeries_surgery_name_label = tk.Label(self.patient_surgeries_labelframe)
        self.patient_surgeries_surgery_name_label.place(relx=0.078, rely=0.245
                                                        , height=21, width=97, bordermode='ignore')
        self.patient_surgeries_surgery_name_label.configure(activebackground="#f9f9f9")
        self.patient_surgeries_surgery_name_label.configure(text='''Surgery Name''')
        #
        # self.patient_surgeries_reason_label = tk.Label(self.patient_surgeries_labelframe)
        # self.patient_surgeries_reason_label.place(relx=0.469, rely=0.245
        #                                           , height=21, width=52, bordermode='ignore')
        # self.patient_surgeries_reason_label.configure(activebackground="#f9f9f9")
        # self.patient_surgeries_reason_label.configure(text='''Reason''')

        self.Listbox2 = tk.Listbox(self.patient_surgeries_labelframe)
        self.Listbox2.place(relx=0.016, rely=0.571, relheight=0.351
                            , relwidth=0.959, bordermode='ignore')
        self.Listbox2.configure(background="white")
        self.Listbox2.configure(font="TkFixedFont")
        self.Listbox2.configure(selectbackground="#c4c4c4")
        self.Listbox2.configure(width=614)

        self.patient_surgeries_patientssn_label = tk.Label(self.patient_surgeries_labelframe)
        self.patient_surgeries_patientssn_label.place(relx=0.078, rely=0.122
                                                      , height=21, width=80, bordermode='ignore')
        self.patient_surgeries_patientssn_label.configure(activebackground="#f9f9f9")
        self.patient_surgeries_patientssn_label.configure(text='''Patient SSN''')

        self.patient_surgeries_surgeryID_label = tk.Label(self.patient_surgeries_labelframe)
        self.patient_surgeries_surgeryID_label.place(relx=0.438, rely=0.122
                                                     , height=21, width=72, bordermode='ignore')
        self.patient_surgeries_surgeryID_label.configure(activebackground="#f9f9f9")
        self.patient_surgeries_surgeryID_label.configure(text='''Surgery ID''')

        self.patient_surgeries_result_label = tk.Label(self.patient_surgeries_labelframe)
        self.patient_surgeries_result_label.place(relx=0.688, rely=0.449
                                                  , height=21, width=45, bordermode='ignore')
        self.patient_surgeries_result_label.configure(activebackground="#f9f9f9")
        self.patient_surgeries_result_label.configure(text='''Result''')

        self.patient_surgeries_end_date_label = tk.Label(self.patient_surgeries_labelframe)
        self.patient_surgeries_end_date_label.place(relx=0.734, rely=0.286
                                                    , height=21, width=63, bordermode='ignore')
        self.patient_surgeries_end_date_label.configure(activebackground="#f9f9f9")
        self.patient_surgeries_end_date_label.configure(text='''End Date''')

        self.patient_surgeries_start_date_label = tk.Label(self.patient_surgeries_labelframe)
        self.patient_surgeries_start_date_label.place(relx=0.734, rely=0.122
                                                      , height=21, width=70, bordermode='ignore')
        self.patient_surgeries_start_date_label.configure(activebackground="#f9f9f9")
        self.patient_surgeries_start_date_label.configure(text='''Start Date''')

        self.patient_surgeries_patient_ssn_textbox = tk.Text(self.patient_surgeries_labelframe)
        self.patient_surgeries_patient_ssn_textbox.place(relx=0.219, rely=0.122
                                                         , relheight=0.098, relwidth=0.166, bordermode='ignore')
        self.patient_surgeries_patient_ssn_textbox.configure(background="white")
        self.patient_surgeries_patient_ssn_textbox.configure(font="TkTextFont")
        self.patient_surgeries_patient_ssn_textbox.configure(selectbackground="#c4c4c4")
        self.patient_surgeries_patient_ssn_textbox.configure(width=106)
        self.patient_surgeries_patient_ssn_textbox.configure(wrap='word')

        self.patient_surgeries_end_date_textbox = tk.Text(self.patient_surgeries_labelframe)
        self.patient_surgeries_end_date_textbox.place(relx=0.844, rely=0.286
                                                      , relheight=0.098, relwidth=0.134, bordermode='ignore')
        self.patient_surgeries_end_date_textbox.configure(background="white")
        self.patient_surgeries_end_date_textbox.configure(font="TkTextFont")
        self.patient_surgeries_end_date_textbox.configure(selectbackground="#c4c4c4")
        self.patient_surgeries_end_date_textbox.configure(width=86)
        self.patient_surgeries_end_date_textbox.configure(wrap='word')

        self.patient_surgeries_start_date_textbox = tk.Text(self.patient_surgeries_labelframe)
        self.patient_surgeries_start_date_textbox.place(relx=0.844, rely=0.122
                                                        , relheight=0.098, relwidth=0.134, bordermode='ignore')
        self.patient_surgeries_start_date_textbox.configure(background="white")
        self.patient_surgeries_start_date_textbox.configure(font="TkTextFont")
        self.patient_surgeries_start_date_textbox.configure(selectbackground="#c4c4c4")
        self.patient_surgeries_start_date_textbox.configure(width=86)
        self.patient_surgeries_start_date_textbox.configure(wrap='word')

        self.patient_surgeries_surgeryID_textbox = tk.Text(self.patient_surgeries_labelframe)
        self.patient_surgeries_surgeryID_textbox.place(relx=0.563, rely=0.122
                                                       , relheight=0.098, relwidth=0.103, bordermode='ignore')
        self.patient_surgeries_surgeryID_textbox.configure(background="white")
        self.patient_surgeries_surgeryID_textbox.configure(font="TkTextFont")
        self.patient_surgeries_surgeryID_textbox.configure(selectbackground="#c4c4c4")
        self.patient_surgeries_surgeryID_textbox.configure(width=66)
        self.patient_surgeries_surgeryID_textbox.configure(wrap='word')

        self.patient_surgeries_surgery_name_textbox = tk.Text(self.patient_surgeries_labelframe)
        self.patient_surgeries_surgery_name_textbox.place(relx=0.25, rely=0.245
                                                          , relheight=0.098, relwidth=0.166, bordermode='ignore')
        self.patient_surgeries_surgery_name_textbox.configure(background="white")
        self.patient_surgeries_surgery_name_textbox.configure(font="TkTextFont")
        self.patient_surgeries_surgery_name_textbox.configure(selectbackground="#c4c4c4")
        self.patient_surgeries_surgery_name_textbox.configure(width=106)
        self.patient_surgeries_surgery_name_textbox.configure(wrap='word')

        self.patient_surgeries_result_textbox = tk.Text(self.patient_surgeries_labelframe)
        self.patient_surgeries_result_textbox.place(relx=0.766, rely=0.449
                                                    , relheight=0.098, relwidth=0.213, bordermode='ignore')
        self.patient_surgeries_result_textbox.configure(background="white")
        self.patient_surgeries_result_textbox.configure(font="TkTextFont")
        self.patient_surgeries_result_textbox.configure(selectbackground="#c4c4c4")
        self.patient_surgeries_result_textbox.configure(width=136)
        self.patient_surgeries_result_textbox.configure(wrap='word')

        # self.patient_surgeries_reason_textbox = tk.Text(self.patient_surgeries_labelframe)
        # self.patient_surgeries_reason_textbox.place(relx=0.563, rely=0.245
        #                                             , relheight=0.098, relwidth=0.15, bordermode='ignore')
        # self.patient_surgeries_reason_textbox.configure(background="white")
        # self.patient_surgeries_reason_textbox.configure(font="TkTextFont")
        # self.patient_surgeries_reason_textbox.configure(selectbackground="#c4c4c4")
        # self.patient_surgeries_reason_textbox.configure(width=96)
        # self.patient_surgeries_reason_textbox.configure(wrap='word')

        self.patient_surgeries_yyyymmdd_startdate_label = tk.Label(self.patient_surgeries_labelframe)
        self.patient_surgeries_yyyymmdd_startdate_label.place(relx=0.859
                                                              , rely=0.082, height=11, width=56, bordermode='ignore')
        self.patient_surgeries_yyyymmdd_startdate_label.configure(activebackground="#f9f9f9")
        self.patient_surgeries_yyyymmdd_startdate_label.configure(font=font9)
        self.patient_surgeries_yyyymmdd_startdate_label.configure(text='''YYYYMMDD''')

        self.patient_surgeries_yyyymmdd_enddate_label = tk.Label(self.patient_surgeries_labelframe)
        self.patient_surgeries_yyyymmdd_enddate_label.place(relx=0.859
                                                            , rely=0.245, height=11, width=56, bordermode='ignore')
        self.patient_surgeries_yyyymmdd_enddate_label.configure(activebackground="#f9f9f9")
        self.patient_surgeries_yyyymmdd_enddate_label.configure(font=font9)
        self.patient_surgeries_yyyymmdd_enddate_label.configure(text='''YYYYMMDD''')

        self.patient_surgeries_show_surgeries_button = tk.Button(self.patient_surgeries_labelframe)
        self.patient_surgeries_show_surgeries_button.place(relx=0.016, rely=0.408
                                                           , height=29, width=126, bordermode='ignore')
        self.patient_surgeries_show_surgeries_button.configure(activebackground="#d9d9d9")
        self.patient_surgeries_show_surgeries_button.configure(text='''Show Surgeries''')
        self.patient_surgeries_show_surgeries_button.configure(command=self.show_surgery)

        self.patient_surgeries_update_button = tk.Button(self.patient_surgeries_labelframe)
        self.patient_surgeries_update_button.place(relx=0.25, rely=0.408
                                                   , height=29, width=113, bordermode='ignore')
        self.patient_surgeries_update_button.configure(activebackground="#d9d9d9")
        self.patient_surgeries_update_button.configure(text='''Update''')
        self.patient_surgeries_update_button.configure(command=self.update_surgery)

        self.patient_surgeries_submit_button = tk.Button(self.patient_surgeries_labelframe)
        self.patient_surgeries_submit_button.place(relx=0.469, rely=0.408
                                                   , height=29, width=119, bordermode='ignore')
        self.patient_surgeries_submit_button.configure(activebackground="#d9d9d9")
        self.patient_surgeries_submit_button.configure(text='''Submit''')
        self.patient_surgeries_submit_button.configure(command=self.insert_patient_surgery)

        self.patient_info_labelframe = tk.LabelFrame(top)
        self.patient_info_labelframe.place(relx=0.015, rely=0.027
                                           , relheight=0.254, relwidth=0.466)
        self.patient_info_labelframe.configure(relief='groove')
        self.patient_info_labelframe.configure(text='''Patient Information''')
        self.patient_info_labelframe.configure(width=640)

        self.patient_information_patient_ssn_label = tk.Label(self.patient_info_labelframe)
        self.patient_information_patient_ssn_label.place(relx=0.001, rely=0.108
                                                         , height=21, width=80, bordermode='ignore')
        self.patient_information_patient_ssn_label.configure(activebackground="#f9f9f9")
        self.patient_information_patient_ssn_label.configure(text='''Patient SSN''')

        self.patient_information_patientssn_textbox = tk.Text(self.patient_info_labelframe)
        self.patient_information_patientssn_textbox.place(relx=0.117, rely=0.108
                                                          , relheight=0.13, relwidth=0.166, bordermode='ignore')
        self.patient_information_patientssn_textbox.configure(background="white")
        self.patient_information_patientssn_textbox.configure(font="TkTextFont")
        self.patient_information_patientssn_textbox.configure(selectbackground="#c4c4c4")
        self.patient_information_patientssn_textbox.configure(width=106)
        self.patient_information_patientssn_textbox.configure(wrap='word')

        self.Listbox3 = tk.Listbox(self.patient_info_labelframe)
        self.Listbox3.place(relx=0.016, rely=0.595, relheight=0.303
                            , relwidth=0.959, bordermode='ignore')
        self.Listbox3.configure(background="white")
        self.Listbox3.configure(font="TkFixedFont")
        self.Listbox3.configure(selectbackground="#c4c4c4")
        self.Listbox3.configure(width=614)

        self.patient_info_fullname_label = tk.Label(self.patient_info_labelframe)
        self.patient_info_fullname_label.place(relx=0.29, rely=0.108, height=21
                                               , width=71, bordermode='ignore')
        self.patient_info_fullname_label.configure(activebackground="#f9f9f9")
        self.patient_info_fullname_label.configure(text='''Full Name''')

        self.patient_info_fullname_textbox = tk.Text(self.patient_info_labelframe)
        self.patient_info_fullname_textbox.place(relx=0.4, rely=0.108
                                                 , relheight=0.13, relwidth=0.213, bordermode='ignore')
        self.patient_info_fullname_textbox.configure(background="white")
        self.patient_info_fullname_textbox.configure(font="TkTextFont")
        self.patient_info_fullname_textbox.configure(selectbackground="#c4c4c4")
        self.patient_info_fullname_textbox.configure(width=136)
        self.patient_info_fullname_textbox.configure(wrap='word')

        self.patient_info_DOB_label = tk.Label(self.patient_info_labelframe)
        self.patient_info_DOB_label.place(relx=0.630, rely=0.108, height=21
                                          , width=33, bordermode='ignore')
        self.patient_info_DOB_label.configure(activebackground="#f9f9f9")
        self.patient_info_DOB_label.configure(text='''DOB''')

        self.patient_info_DOB_textbox = tk.Text(self.patient_info_labelframe)
        self.patient_info_DOB_textbox.place(relx=0.684, rely=0.108
                                            , relheight=0.13, relwidth=0.110, bordermode='ignore')
        self.patient_info_DOB_textbox.configure(background="white")
        self.patient_info_DOB_textbox.configure(font="TkTextFont")
        self.patient_info_DOB_textbox.configure(selectbackground="#c4c4c4")
        self.patient_info_DOB_textbox.configure(width=86)
        self.patient_info_DOB_textbox.configure(wrap='word')

        self.patient_info_yyyymmdd_label = tk.Label(self.patient_info_labelframe)
        self.patient_info_yyyymmdd_label.place(relx=0.70, rely=0.054, height=11
                                               , width=61, bordermode='ignore')
        self.patient_info_yyyymmdd_label.configure(activebackground="#f9f9f9")
        self.patient_info_yyyymmdd_label.configure(font=font9)
        self.patient_info_yyyymmdd_label.configure(text='''YYYYMMDD''')

        self.patient_info_address_label = tk.Label(self.patient_info_labelframe)
        self.patient_info_address_label.place(relx=0.016, rely=0.27, height=21
                                              , width=56, bordermode='ignore')
        self.patient_info_address_label.configure(activebackground="#f9f9f9")
        self.patient_info_address_label.configure(text='''Address''')

        self.patient_info_address_textbox = tk.Text(self.patient_info_labelframe)
        self.patient_info_address_textbox.place(relx=0.109, rely=0.27
                                                , relheight=0.13, relwidth=0.259, bordermode='ignore')
        self.patient_info_address_textbox.configure(background="white")
        self.patient_info_address_textbox.configure(font="TkTextFont")
        self.patient_info_address_textbox.configure(selectbackground="#c4c4c4")
        self.patient_info_address_textbox.configure(width=166)
        self.patient_info_address_textbox.configure(wrap='word')

        self.patient_info_gender_label = tk.Label(self.patient_info_labelframe)
        self.patient_info_gender_label.place(relx=0.79, rely=0.108, height=21
                                             , width=61, bordermode='ignore')
        self.patient_info_gender_label.configure(activebackground="#f9f9f9")
        self.patient_info_gender_label.configure(text='''Gender''')

        self.patient_info_gender_textbox = tk.Text(self.patient_info_labelframe)
        self.patient_info_gender_textbox.place(relx=0.88, rely=0.108
                                               , relheight=0.13, relwidth=0.088, bordermode='ignore')
        self.patient_info_gender_textbox.configure(background="white")
        self.patient_info_gender_textbox.configure(font="TkTextFont")
        self.patient_info_gender_textbox.configure(selectbackground="#c4c4c4")
        self.patient_info_gender_textbox.configure(width=56)
        self.patient_info_gender_textbox.configure(wrap='word')

        self.patient_info_phone_label = tk.Label(self.patient_info_labelframe)
        self.patient_info_phone_label.place(relx=0.370, rely=0.27, height=21
                                            , width=59, bordermode='ignore')
        self.patient_info_phone_label.configure(activebackground="#f9f9f9")
        self.patient_info_phone_label.configure(text='''Phone #''')

        # Phone textbox
        self.Text5 = tk.Text(self.patient_info_labelframe)
        self.Text5.place(relx=0.460, rely=0.27, relheight=0.13, relwidth=0.131
                         , bordermode='ignore')
        self.Text5.configure(background="white")
        self.Text5.configure(font="TkTextFont")
        self.Text5.configure(selectbackground="#c4c4c4")
        self.Text5.configure(width=116)
        self.Text5.configure(wrap='word')

        self.patient_emergency_contact_name_label = tk.Label(self.patient_info_labelframe)
        self.patient_emergency_contact_name_label.place(relx=0.60, rely=0.27, height=21
                                            , width=85, bordermode='ignore')
        self.patient_emergency_contact_name_label.configure(activebackground="#f9f9f9")
        self.patient_emergency_contact_name_label.configure(text='''Contact Name''')

        self.patient_emergencycontact_name_textbox = tk.Text(self.patient_info_labelframe)
        self.patient_emergencycontact_name_textbox.place(relx=0.75, rely=0.27
                                                 , relheight=0.13, relwidth=0.213, bordermode='ignore')
        self.patient_emergencycontact_name_textbox.configure(background="white")
        self.patient_emergencycontact_name_textbox.configure(font="TkTextFont")
        self.patient_emergencycontact_name_textbox.configure(selectbackground="#c4c4c4")
        self.patient_emergencycontact_name_textbox.configure(width=136)
        self.patient_emergencycontact_name_textbox.configure(wrap='word')

        self.patient_info_emergency_contact_phone_label = tk.Label(self.patient_info_labelframe)
        self.patient_info_emergency_contact_phone_label.place(relx=0.016
                                                              , rely=0.432, height=21, width=190, bordermode='ignore')
        self.patient_info_emergency_contact_phone_label.configure(activebackground="#f9f9f9")
        self.patient_info_emergency_contact_phone_label.configure(text='''Emergency Contact Phone #''')

        self.patient_info_emergency_contact_phone_textbox = tk.Text(self.patient_info_labelframe)
        self.patient_info_emergency_contact_phone_textbox.place(relx=0.313
                                                                , rely=0.432, relheight=0.13, relwidth=0.213
                                                                , bordermode='ignore')
        self.patient_info_emergency_contact_phone_textbox.configure(background="white")
        self.patient_info_emergency_contact_phone_textbox.configure(font="TkTextFont")
        self.patient_info_emergency_contact_phone_textbox.configure(selectbackground="#c4c4c4")
        self.patient_info_emergency_contact_phone_textbox.configure(width=136)
        self.patient_info_emergency_contact_phone_textbox.configure(wrap='word')

        self.patient_info_show_button = tk.Button(self.patient_info_labelframe)
        self.patient_info_show_button.place(relx=0.563, rely=0.432, height=29
                                            , width=141, bordermode='ignore')
        self.patient_info_show_button.configure(activebackground="#d9d9d9")
        self.patient_info_show_button.configure(text='''Show Information''')
        self.patient_info_show_button.configure(command=self.show_patient_info)

        self.patient_info_update_button = tk.Button(self.patient_info_labelframe)
        self.patient_info_update_button.place(relx=0.813, rely=0.432, height=29
                                              , width=103, bordermode='ignore')
        self.patient_info_update_button.configure(activebackground="#d9d9d9")
        self.patient_info_update_button.configure(text='''Update''')
        self.patient_info_update_button.configure(width=103)
        self.patient_info_update_button.configure(command=self.update_patient_info)


if __name__ == '__main__':
    vp_start_gui()
